mobile_detect:
  redirect:
    full:
      action: redirect            # redirect, no_redirect, redirect_without_path
      host: http://sortir.com       # with scheme (http|https), default null, url validate
      is_enabled: true            # default false
      status_code: 301            # default 302
    mobile:
      action: redirect            # redirect, no_redirect, redirect_without_path
      host: http://m.sortir.com     # with scheme (http|https), default null, url validate
      is_enabled: true            # default false
      status_code: 301            # default 302
    tablet:
      action: redirect            # redirect, no_redirect, redirect_without_path
      host: http://t.site.com     # with scheme (http|https), default null, url validate
      is_enabled: true            # default false
      status_code: 301            # default 302
    detect_tablet_as_mobile: true # default false

  switch_device_view:
    save_referer_path: false                  # default true
      # true  redirectUrl = http://site.com/current/path?currentQuery=string
    # false redirectUrl = http://site.com
  cookie_expire_datetime_modifier: '+1s' # default
  cookie_key: 'device_view'                   # default
  switch_param: 'device_view'                 # default